/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SalesTrack.Action;
import javax.swing.JButton;
import javax.swing.JPanel;
import AplicationEnums.Functionality;
import SalesTrack.Credit.AddCreditPanel;
import SalesTrack.Credit.DeleteCreditPanel;
import SalesTrack.Credit.UpdateCreditPanel;
import SalesTrack.Credit.ViewCreditPanel;
import SalesTrack.Expense.AddExpensePanel;
import SalesTrack.Expense.DeleteExpensePanel;
import SalesTrack.Expense.UpdateExpensePanel;
import SalesTrack.Expense.ViewExpensePanel;
import SalesTrack.Income.AddIncomePanel;
import SalesTrack.Income.DeleteIncomePanel;
import SalesTrack.Income.UpdateIncomePanel;
import SalesTrack.Income.ViewIncomePanel;
import SalesTrack.Sales.AddSalesPanel;
import SalesTrack.Sales.DeleteSalesPanel;
import SalesTrack.Sales.SalesUpdatePanel;
import SalesTrack.Sales.ViewSalesPanel;
import SalesTrack.Stock.AddStockPanel;
import SalesTrack.Stock.DeleteStockPanel;
import SalesTrack.Stock.StockUpdatePanel;
import SalesTrack.Stock.ViewStockPanel;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class ActionPanel extends javax.swing.JPanel {

    /**
     *  The course panel
     */
    private Functionality option;
    
    
    /**
     * Creates new form CourseActionPanel
     */
    public ActionPanel() {
        initComponents();
    }
     
    /**
     * The parameterized constructor
     * @param panel 
     */
    public ActionPanel(Functionality option)
    {
        initComponents();
        this.option = option;
    }
    
    /**
     * Sets the panel visibility
     * @param panel 
     */
    private void SetPanelVisibility( JPanel panel ){
        
        this.AP_ActionPanelHolder_Panel.removeAll();
        this.AP_ActionPanelHolder_Panel.repaint();
        this.AP_ActionPanelHolder_Panel.revalidate();
        
        this.AP_ActionPanelHolder_Panel.add(panel);
        this.AP_ActionPanelHolder_Panel.repaint();
        this.AP_ActionPanelHolder_Panel.revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CAP_ButtonHolder_Panel = new javax.swing.JPanel();
        ActionPanel_AddButton = new javax.swing.JButton();
        ActionPanel_UpdateButton = new javax.swing.JButton();
        ActionPanel_ViewButton = new javax.swing.JButton();
        ActionPanel_DeleteButton = new javax.swing.JButton();
        AP_ActionPanelHolder_Panel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        CAP_ButtonHolder_Panel.setLayout(new java.awt.GridLayout(1, 0));

        ActionPanel_AddButton.setBackground(new java.awt.Color(51, 153, 0));
        ActionPanel_AddButton.setFont(new java.awt.Font("Miriam Fixed", 1, 12)); // NOI18N
        ActionPanel_AddButton.setForeground(new java.awt.Color(255, 255, 255));
        ActionPanel_AddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SalesTrack/Images/add.png"))); // NOI18N
        ActionPanel_AddButton.setText("New");
        ActionPanel_AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPanel_AddButtonActionPerformed(evt);
            }
        });
        CAP_ButtonHolder_Panel.add(ActionPanel_AddButton);

        ActionPanel_UpdateButton.setBackground(new java.awt.Color(0, 102, 102));
        ActionPanel_UpdateButton.setFont(new java.awt.Font("Miriam Fixed", 1, 12)); // NOI18N
        ActionPanel_UpdateButton.setForeground(new java.awt.Color(255, 255, 255));
        ActionPanel_UpdateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SalesTrack/Images/update.png"))); // NOI18N
        ActionPanel_UpdateButton.setText("Update");
        ActionPanel_UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPanel_UpdateButtonActionPerformed(evt);
            }
        });
        CAP_ButtonHolder_Panel.add(ActionPanel_UpdateButton);

        ActionPanel_ViewButton.setBackground(new java.awt.Color(102, 102, 102));
        ActionPanel_ViewButton.setFont(new java.awt.Font("Miriam Fixed", 1, 12)); // NOI18N
        ActionPanel_ViewButton.setForeground(new java.awt.Color(255, 255, 255));
        ActionPanel_ViewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SalesTrack/Images/view.png"))); // NOI18N
        ActionPanel_ViewButton.setText("View");
        ActionPanel_ViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPanel_ViewButtonActionPerformed(evt);
            }
        });
        CAP_ButtonHolder_Panel.add(ActionPanel_ViewButton);

        ActionPanel_DeleteButton.setBackground(new java.awt.Color(255, 51, 51));
        ActionPanel_DeleteButton.setFont(new java.awt.Font("Miriam Fixed", 1, 12)); // NOI18N
        ActionPanel_DeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        ActionPanel_DeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SalesTrack/Images/delete.png"))); // NOI18N
        ActionPanel_DeleteButton.setText("Delete");
        ActionPanel_DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPanel_DeleteButtonActionPerformed(evt);
            }
        });
        CAP_ButtonHolder_Panel.add(ActionPanel_DeleteButton);

        AP_ActionPanelHolder_Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        AP_ActionPanelHolder_Panel.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CAP_ButtonHolder_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
            .addComponent(AP_ActionPanelHolder_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CAP_ButtonHolder_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(AP_ActionPanelHolder_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
     
    
    /**
     * On clicking the view course button
     * @param evt 
     */
    private void ActionPanel_ViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionPanel_ViewButtonActionPerformed
        if (this.option == Functionality.STOCK)
        {
            ViewStockPanel viewStockPanel = new ViewStockPanel();
            this.SetPanelVisibility(viewStockPanel);
        }
        else if (this.option == Functionality.SALES)
        {
            ViewSalesPanel viewSalesPanel = new ViewSalesPanel();
            this.SetPanelVisibility(viewSalesPanel);
        }
        else if (this.option == Functionality.INCOME)
        {
            ViewIncomePanel viewIncomePanel = new ViewIncomePanel();
            this.SetPanelVisibility(viewIncomePanel);
        }
        else if (this.option == Functionality.EXPENSE)
        {
            ViewExpensePanel viewExpensePanel = new ViewExpensePanel();
            this.SetPanelVisibility(viewExpensePanel);
        }
        else if (this.option == Functionality.CREDIT)
        {
            ViewCreditPanel viewCreditPanel = new ViewCreditPanel();
            this.SetPanelVisibility(viewCreditPanel);
        }
    }//GEN-LAST:event_ActionPanel_ViewButtonActionPerformed

    /**
     * On clicking new button 
     * @param evt 
     */
    private void ActionPanel_AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionPanel_AddButtonActionPerformed
        if (this.option == Functionality.STOCK)
        {
            AddStockPanel addStockPanel = new AddStockPanel();
            this.SetPanelVisibility(addStockPanel);
        }
        else if (this.option == Functionality.SALES)
        {
            AddSalesPanel addSalesPanel = new AddSalesPanel();
            this.SetPanelVisibility(addSalesPanel);
        }
        else if (this.option == Functionality.INCOME)
        {
            AddIncomePanel addIncomePanel = new AddIncomePanel();
            this.SetPanelVisibility(addIncomePanel);
        }
        else if (this.option == Functionality.EXPENSE)
        {
            AddExpensePanel addExpensePanel = new AddExpensePanel();
            this.SetPanelVisibility(addExpensePanel);
        }
        else if (this.option == Functionality.CREDIT)
        {
            AddCreditPanel addCreditPanel = new AddCreditPanel();
            this.SetPanelVisibility(addCreditPanel);
        }
    }//GEN-LAST:event_ActionPanel_AddButtonActionPerformed

    /**
     * On clicking the update course button
     * @param evt 
     */
    private void ActionPanel_UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionPanel_UpdateButtonActionPerformed
        if (this.option == Functionality.STOCK)
        {
            StockUpdatePanel stockUpdatePanel = new StockUpdatePanel();
            this.SetPanelVisibility(stockUpdatePanel);
        }
        else if (this.option == Functionality.SALES)
        {
            SalesUpdatePanel salesUpdatePanel = new SalesUpdatePanel();
            this.SetPanelVisibility(salesUpdatePanel);
        }
        else if (this.option == Functionality.INCOME)
        {
            UpdateIncomePanel updateIncomePanel = new UpdateIncomePanel();
            this.SetPanelVisibility(updateIncomePanel);
        }
        else if (this.option == Functionality.EXPENSE)
        {
            UpdateExpensePanel updateExpensePanel = new UpdateExpensePanel();
            this.SetPanelVisibility(updateExpensePanel);
        }
        else if (this.option == Functionality.CREDIT)
        {
            UpdateCreditPanel updateCreditPanel = new UpdateCreditPanel();
            this.SetPanelVisibility(updateCreditPanel);
        }
    }//GEN-LAST:event_ActionPanel_UpdateButtonActionPerformed

    /**
     * On clicking the delete course button
     * @param evt 
     */
    private void ActionPanel_DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionPanel_DeleteButtonActionPerformed

        if (this.option == Functionality.STOCK)
        {
            DeleteStockPanel deleteStockPanel = new DeleteStockPanel();
            this.SetPanelVisibility(deleteStockPanel);
        }
        else if (this.option == Functionality.SALES)
        {
            DeleteSalesPanel deleteSalesPanel = new DeleteSalesPanel();
            this.SetPanelVisibility(deleteSalesPanel);
        }
        else if (this.option == Functionality.INCOME)
        {
            DeleteIncomePanel deleteIncomePanel = new DeleteIncomePanel();
            this.SetPanelVisibility(deleteIncomePanel);
        }
        else if (this.option == Functionality.EXPENSE)
        {
            DeleteExpensePanel deleteExpensePanel = new DeleteExpensePanel();
            this.SetPanelVisibility(deleteExpensePanel);
        }
        else if (this.option == Functionality.CREDIT)
        {
            DeleteCreditPanel deleteCreditPanel = new DeleteCreditPanel();
            this.SetPanelVisibility(deleteCreditPanel);
        }
    }//GEN-LAST:event_ActionPanel_DeleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AP_ActionPanelHolder_Panel;
    private javax.swing.JButton ActionPanel_AddButton;
    private javax.swing.JButton ActionPanel_DeleteButton;
    private javax.swing.JButton ActionPanel_UpdateButton;
    private javax.swing.JButton ActionPanel_ViewButton;
    private javax.swing.JPanel CAP_ButtonHolder_Panel;
    // End of variables declaration//GEN-END:variables
}
