/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SalesTrack.Expense;

import SalesTrack.Income.*;
import SalesTrack.Stock.*;
import AplicationEnums.Actions;
import Database.ExpenseManager;
import Database.IncomeManager;
import SalesTrack.Models.Expense;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author User
 */
public class DeleteExpensePanel extends javax.swing.JPanel {

    
   
   /**
    * The action being made
    */
   private Actions action;
   
   private ArrayList<Expense> expenses ;
   
    /**
     * Creates new form ShortTermCourse
     */
    public DeleteExpensePanel() {
        initComponents();
        this.ShowAllExpenseDetails();
    }

    /**
     * Sets the table for displaying all the available incomes
     */
    public  void ShowAllExpenseDetails()
    {
        try{
            DefaultTableModel dm = (DefaultTableModel)DEP_Expense_Table.getModel();
            dm.setRowCount(0);
            this.expenses = new ExpenseManager().GetAllExpensesAvailable();
            if(null != expenses)
            {
                expenses.stream().forEach((stock) -> 
                {
                    dm.addRow(new Object[]
                    {
                        stock.GetID(),
                        stock.GetName(),
                        stock.GetAmount(),
                        stock.GetDate()
                     });
                });
            }
        } 
        catch (ClassNotFoundException | SQLException ex) 
        {
           JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    /**
     * Creates a new instance of the panel and sets the course type
     * Also identifies the action being made
     */
 /*   public ViewStockPanel(CourseType type, Actions action) {
        initComponents();
        this.courseType = type;
        this.action = action;  
        this.FilterButtonHolder();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DEP_ItemsHolder_Panel = new javax.swing.JPanel();
        DEP_TableHolder_Panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DEP_Expense_Table = new javax.swing.JTable();
        DeleteExpense_Button = new javax.swing.JButton();
        DEP_search_TF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Delete expense details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Miriam Fixed", 0, 11))); // NOI18N

        DEP_ItemsHolder_Panel.setBackground(new java.awt.Color(163, 197, 204));
        DEP_ItemsHolder_Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        DEP_TableHolder_Panel.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setFont(new java.awt.Font("Miriam Fixed", 1, 11)); // NOI18N

        DEP_Expense_Table.setFont(new java.awt.Font("Miriam Fixed", 0, 12)); // NOI18N
        DEP_Expense_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "StockID", "StockName"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DEP_Expense_Table.setRowHeight(28);
        DEP_Expense_Table.setRowMargin(5);
        jScrollPane1.setViewportView(DEP_Expense_Table);

        javax.swing.GroupLayout DEP_TableHolder_PanelLayout = new javax.swing.GroupLayout(DEP_TableHolder_Panel);
        DEP_TableHolder_Panel.setLayout(DEP_TableHolder_PanelLayout);
        DEP_TableHolder_PanelLayout.setHorizontalGroup(
            DEP_TableHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );
        DEP_TableHolder_PanelLayout.setVerticalGroup(
            DEP_TableHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DEP_TableHolder_PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        DeleteExpense_Button.setBackground(new java.awt.Color(255, 51, 51));
        DeleteExpense_Button.setFont(new java.awt.Font("Miriam Fixed", 1, 12)); // NOI18N
        DeleteExpense_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SalesTrack/Images/delete.png"))); // NOI18N
        DeleteExpense_Button.setText("Delete");
        DeleteExpense_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteExpense_ButtonActionPerformed(evt);
            }
        });

        DEP_search_TF.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N
        DEP_search_TF.setMinimumSize(new java.awt.Dimension(5, 20));
        DEP_search_TF.setPreferredSize(new java.awt.Dimension(5, 20));
        DEP_search_TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DEP_search_TFKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Miriam Fixed", 0, 12)); // NOI18N
        jLabel1.setText("Type here to search..");

        javax.swing.GroupLayout DEP_ItemsHolder_PanelLayout = new javax.swing.GroupLayout(DEP_ItemsHolder_Panel);
        DEP_ItemsHolder_Panel.setLayout(DEP_ItemsHolder_PanelLayout);
        DEP_ItemsHolder_PanelLayout.setHorizontalGroup(
            DEP_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DEP_ItemsHolder_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DEP_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DEP_TableHolder_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(DEP_ItemsHolder_PanelLayout.createSequentialGroup()
                        .addComponent(DEP_search_TF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(147, 147, 147)
                        .addComponent(DeleteExpense_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DEP_ItemsHolder_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        DEP_ItemsHolder_PanelLayout.setVerticalGroup(
            DEP_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DEP_ItemsHolder_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DEP_TableHolder_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DEP_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DeleteExpense_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DEP_search_TF, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DEP_ItemsHolder_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DEP_ItemsHolder_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteExpense_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteExpense_ButtonActionPerformed
        // Deleting an income
        ExpenseManager expenseManager = null;
        ResultSet rs = null;
        int confirm = 0;
        boolean isDeleted = false;
        if(DEP_Expense_Table.getSelectedRow() >= 0)
        {
            // Showing a confirmation dialog
            confirm = JOptionPane.showConfirmDialog(null, "Are you sure, that you want to delete the selected expense details?");
            
            if (0 == confirm)
            {
                try
                {
                    expenseManager = new ExpenseManager();
                    isDeleted = expenseManager.DeleteExpenseDetails(String.valueOf(DEP_Expense_Table.getValueAt(DEP_Expense_Table.getSelectedRow(), 0)));
                    if(isDeleted)
                    {
                        JOptionPane.showMessageDialog(null, "Record has been deleted...");
                        this.ShowAllExpenseDetails();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Record could not be deleted...");
                    }   
                }
                catch (ClassNotFoundException | SQLException ex)
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, " Please select a row to continue...");
        }
    }//GEN-LAST:event_DeleteExpense_ButtonActionPerformed

    private void DEP_search_TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DEP_search_TFKeyReleased
        // When search words are typed on the search textfield
        ExpenseManager expenseManager = null; 
        ResultSet rs = null; 
        
        String searchedValue = DEP_search_TF.getText();
        if( searchedValue.length() > 0 )
        {
            try 
            {
                expenseManager = new ExpenseManager();
                rs = expenseManager.GetExpenseDetailsOnSearching(searchedValue);
                if ( null == rs )
                {
                    
                }
                else
                {
                   DEP_Expense_Table.setModel(DbUtils.resultSetToTableModel(rs));
                }
                
                // deallocation
                expenseManager.closeConection();
                expenseManager    = null;
                rs         = null;
                
            } 
            catch (ClassNotFoundException | SQLException ex) 
            {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_DEP_search_TFKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DEP_Expense_Table;
    private javax.swing.JPanel DEP_ItemsHolder_Panel;
    private javax.swing.JPanel DEP_TableHolder_Panel;
    private javax.swing.JTextField DEP_search_TF;
    private javax.swing.JButton DeleteExpense_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
