/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SalesTrack.Expense;

import SalesTrack.Income.*;
import SalesTrack.Stock.*;
import AplicationEnums.Actions;
import Database.ExpenseManager;
import Database.IncomeManager;
import SalesTrack.Models.Expense;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author User
 */
public class ViewExpensePanel extends javax.swing.JPanel {

    
   
   /**
    * The action being made
    */
   private Actions action;
   
    private ArrayList<Expense> expenses ;
   
    /**
     * Creates new form ShortTermCourse
     */
    public ViewExpensePanel() {
        initComponents();
        this.ShowAllExpenseDetails();
    }

    /**
     * Sets the table for displaying all the available expenses
     */
    public  void ShowAllExpenseDetails()
    {
        try{
            DefaultTableModel dm = (DefaultTableModel)VEP_Expense_Table.getModel();
            dm.setRowCount(0);
            this.expenses = new ExpenseManager().GetAllExpensesAvailable();
            if(null != expenses)
            {
                expenses.stream().forEach((stock) -> 
                {
                    dm.addRow(new Object[]
                    {
                        stock.GetID(),
                        stock.GetName(),
                        stock.GetAmount(),
                        stock.GetDate()
                     });
                });
            }
        } 
        catch (ClassNotFoundException | SQLException ex) 
        {
           JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    /**
     * Creates a new instance of the panel and sets the course type
     * Also identifies the action being made
     */
 /*   public ViewExpensePanel(CourseType type, Actions action) {
        initComponents();
        this.courseType = type;
        this.action = action;  
        this.FilterButtonHolder();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VEP_ItemsHolder_Panel = new javax.swing.JPanel();
        VEP_TableHolder_Panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        VEP_Expense_Table = new javax.swing.JTable();
        VEP_search_TF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "View expense details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Miriam Fixed", 0, 11))); // NOI18N

        VEP_ItemsHolder_Panel.setBackground(new java.awt.Color(163, 197, 204));
        VEP_ItemsHolder_Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        VEP_TableHolder_Panel.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setFont(new java.awt.Font("Miriam Fixed", 1, 11)); // NOI18N

        VEP_Expense_Table.setFont(new java.awt.Font("Miriam Fixed", 0, 12)); // NOI18N
        VEP_Expense_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Income ID", "Income details", "Amount", "Added date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        VEP_Expense_Table.setRowHeight(28);
        VEP_Expense_Table.setRowMargin(5);
        jScrollPane1.setViewportView(VEP_Expense_Table);

        javax.swing.GroupLayout VEP_TableHolder_PanelLayout = new javax.swing.GroupLayout(VEP_TableHolder_Panel);
        VEP_TableHolder_Panel.setLayout(VEP_TableHolder_PanelLayout);
        VEP_TableHolder_PanelLayout.setHorizontalGroup(
            VEP_TableHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );
        VEP_TableHolder_PanelLayout.setVerticalGroup(
            VEP_TableHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VEP_TableHolder_PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        VEP_search_TF.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N
        VEP_search_TF.setMinimumSize(new java.awt.Dimension(5, 20));
        VEP_search_TF.setPreferredSize(new java.awt.Dimension(5, 20));
        VEP_search_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VEP_search_TFActionPerformed(evt);
            }
        });
        VEP_search_TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                VEP_search_TFKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Miriam Fixed", 0, 12)); // NOI18N
        jLabel1.setText("Type here to search..");

        javax.swing.GroupLayout VEP_ItemsHolder_PanelLayout = new javax.swing.GroupLayout(VEP_ItemsHolder_Panel);
        VEP_ItemsHolder_Panel.setLayout(VEP_ItemsHolder_PanelLayout);
        VEP_ItemsHolder_PanelLayout.setHorizontalGroup(
            VEP_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VEP_ItemsHolder_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VEP_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VEP_TableHolder_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(VEP_ItemsHolder_PanelLayout.createSequentialGroup()
                        .addComponent(VEP_search_TF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        VEP_ItemsHolder_PanelLayout.setVerticalGroup(
            VEP_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VEP_ItemsHolder_PanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(VEP_TableHolder_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(VEP_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VEP_search_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VEP_ItemsHolder_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VEP_ItemsHolder_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void VEP_search_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VEP_search_TFActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_VEP_search_TFActionPerformed

    private void VEP_search_TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VEP_search_TFKeyReleased
        // When search words are typed on the search textfield
        ExpenseManager expenseManager = null; 
        ResultSet rs = null; 
        
        String searchedValue = VEP_search_TF.getText();
        if( searchedValue.length() > 0 )
        {
            try 
            {
                expenseManager = new ExpenseManager();
                rs = expenseManager.GetExpenseDetailsOnSearching(searchedValue);
                if ( null == rs )
                {
                    
                }
                else
                {
                   VEP_Expense_Table.setModel(DbUtils.resultSetToTableModel(rs));
                }
                
                // deallocation
                expenseManager.closeConection();
                expenseManager    = null;
                rs         = null;
                
            } 
            catch (ClassNotFoundException | SQLException ex) 
            {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_VEP_search_TFKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable VEP_Expense_Table;
    private javax.swing.JPanel VEP_ItemsHolder_Panel;
    private javax.swing.JPanel VEP_TableHolder_Panel;
    private javax.swing.JTextField VEP_search_TF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
