/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SalesTrack.Sales;

import SalesTrack.Stock.*;
import AplicationEnums.Actions;
import Database.CreditManager;
import Database.SalesManager;
import SalesTrack.Models.Sales;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author User
 */
public class ViewSalesPanel extends javax.swing.JPanel {

    
   
   /**
    * The action being made
    */
   private Actions action;
   
    private ArrayList<Sales> sales ;
    /**
     * Creates new form ShortTermCourse
     */
    public ViewSalesPanel() {
        initComponents();
        this.ShowAllSalesDetails();
    }

    /**
     * Sets the table for displaying all the available expenses
     */
    public  void ShowAllSalesDetails()
    {
        try{
            DefaultTableModel dm = (DefaultTableModel)VSPS_Sales_Table.getModel();
            dm.setRowCount(0);
            this.sales = new SalesManager().GetAllSalesAvailable();
            if(null != sales)
            {
                sales.stream().forEach((sale) -> 
                {
                    dm.addRow(new Object[]
                    {
                        sale.GetID(),
                        sale.GetStockID(),
                        sale.GetStockName(),
                        sale.GetQuantity(),
                        sale.GetAmount(),
                        sale.GetGST(),
                        sale.GetFinalAmount(),
                        sale.GetDate()
                     });
                });
            }
        } 
        catch (ClassNotFoundException | SQLException ex) 
        {
           JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    /**
     * Creates a new instance of the panel and sets the course type
     * Also identifies the action being made
     */
 /*   public ViewSalesPanel(CourseType type, Actions action) {
        initComponents();
        this.courseType = type;
        this.action = action;  
        this.FilterButtonHolder();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VS_ItemsHolder_Panel = new javax.swing.JPanel();
        VS_TableHolder_Panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        VSPS_Sales_Table = new javax.swing.JTable();
        VSPS_search_TF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "View sales details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Miriam Fixed", 0, 11))); // NOI18N

        VS_ItemsHolder_Panel.setBackground(new java.awt.Color(163, 197, 204));
        VS_ItemsHolder_Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        VS_TableHolder_Panel.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setFont(new java.awt.Font("Miriam Fixed", 1, 11)); // NOI18N

        VSPS_Sales_Table.setFont(new java.awt.Font("Miriam Fixed", 0, 12)); // NOI18N
        VSPS_Sales_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Sales ID", "Stock ID", "Stock name", "Quantity", "Amount", "GST", "Final amount", "Sold date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        VSPS_Sales_Table.setRowHeight(28);
        VSPS_Sales_Table.setRowMargin(5);
        jScrollPane1.setViewportView(VSPS_Sales_Table);

        javax.swing.GroupLayout VS_TableHolder_PanelLayout = new javax.swing.GroupLayout(VS_TableHolder_Panel);
        VS_TableHolder_Panel.setLayout(VS_TableHolder_PanelLayout);
        VS_TableHolder_PanelLayout.setHorizontalGroup(
            VS_TableHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );
        VS_TableHolder_PanelLayout.setVerticalGroup(
            VS_TableHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VS_TableHolder_PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        VSPS_search_TF.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N
        VSPS_search_TF.setMinimumSize(new java.awt.Dimension(5, 20));
        VSPS_search_TF.setPreferredSize(new java.awt.Dimension(5, 20));
        VSPS_search_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VSPS_search_TFActionPerformed(evt);
            }
        });
        VSPS_search_TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                VSPS_search_TFKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Miriam Fixed", 0, 12)); // NOI18N
        jLabel1.setText("Type here to search..");

        javax.swing.GroupLayout VS_ItemsHolder_PanelLayout = new javax.swing.GroupLayout(VS_ItemsHolder_Panel);
        VS_ItemsHolder_Panel.setLayout(VS_ItemsHolder_PanelLayout);
        VS_ItemsHolder_PanelLayout.setHorizontalGroup(
            VS_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VS_ItemsHolder_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VS_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VS_TableHolder_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(VS_ItemsHolder_PanelLayout.createSequentialGroup()
                        .addComponent(VSPS_search_TF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(82, 82, 82)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        VS_ItemsHolder_PanelLayout.setVerticalGroup(
            VS_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VS_ItemsHolder_PanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(VS_TableHolder_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(VS_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VSPS_search_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VS_ItemsHolder_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VS_ItemsHolder_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void VSPS_search_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VSPS_search_TFActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_VSPS_search_TFActionPerformed

    private void VSPS_search_TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VSPS_search_TFKeyReleased
        // When search words are typed on the search textfield
        SalesManager salesManager = null; 
        ResultSet rs = null; 
        
        String searchedValue = VSPS_search_TF.getText();
        if( searchedValue.length() > 0 )
        {
            try 
            {
                salesManager = new SalesManager();
                rs = salesManager.GetSalesDetailsOnSearching(searchedValue);
                if ( null == rs )
                {
                    
                }
                else
                {
                   VSPS_Sales_Table.setModel(DbUtils.resultSetToTableModel(rs));
                }
                
                // deallocation
                salesManager.closeConection();
                salesManager    = null;
                rs         = null;
                
            } 
            catch (ClassNotFoundException | SQLException ex) 
            {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_VSPS_search_TFKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable VSPS_Sales_Table;
    private javax.swing.JTextField VSPS_search_TF;
    private javax.swing.JPanel VS_ItemsHolder_Panel;
    private javax.swing.JPanel VS_TableHolder_Panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
