/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SalesTrack.Income;
import Database.IncomeManager;
import Database.StockManager;
import SalesTrack.Models.Income;
import SalesTrack.Models.Stock;
import SalesTrack.Stock.*;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;


/**
 *
 * @author Panickar
 */
public class AddIncomePanel extends javax.swing.JPanel {

    /**
     * Creates new form ShortTermCourse
     */
    public AddIncomePanel() {
        initComponents();
    }
    
    private void SetFieldsEmpty()
    {
        AI_Name_TF.setText(null);
        AI_Amount_TF.setText(null);
        ((JTextField)AI_DateChooser.getDateEditor().getUiComponent()).setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddIncomeHolderPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        AI_Name_TF = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        AddIncomeButton = new javax.swing.JButton();
        AI_Amount_TF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AI_DateChooser = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Add income details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Miriam Fixed", 0, 11))); // NOI18N

        AddIncomeHolderPanel.setBackground(new java.awt.Color(204, 219, 222));
        AddIncomeHolderPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N
        jLabel2.setText("Name");

        AI_Name_TF.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N
        AI_Name_TF.setMinimumSize(new java.awt.Dimension(5, 20));
        AI_Name_TF.setPreferredSize(new java.awt.Dimension(5, 20));
        AI_Name_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AI_Name_TFActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N
        jLabel19.setText("Date");

        AddIncomeButton.setBackground(new java.awt.Color(51, 153, 0));
        AddIncomeButton.setFont(new java.awt.Font("Miriam Fixed", 1, 14)); // NOI18N
        AddIncomeButton.setForeground(new java.awt.Color(255, 255, 255));
        AddIncomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SalesTrack/Images/add.png"))); // NOI18N
        AddIncomeButton.setText("Add income");
        AddIncomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddIncomeButtonActionPerformed(evt);
            }
        });

        AI_Amount_TF.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N
        AI_Amount_TF.setMinimumSize(new java.awt.Dimension(5, 20));
        AI_Amount_TF.setPreferredSize(new java.awt.Dimension(5, 20));

        jLabel4.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N
        jLabel4.setText("Amount");

        javax.swing.GroupLayout AddIncomeHolderPanelLayout = new javax.swing.GroupLayout(AddIncomeHolderPanel);
        AddIncomeHolderPanel.setLayout(AddIncomeHolderPanelLayout);
        AddIncomeHolderPanelLayout.setHorizontalGroup(
            AddIncomeHolderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddIncomeHolderPanelLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(AddIncomeHolderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(AddIncomeHolderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AI_Amount_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AI_Name_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AI_DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddIncomeButton))
                .addGap(82, 82, 82))
        );
        AddIncomeHolderPanelLayout.setVerticalGroup(
            AddIncomeHolderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddIncomeHolderPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(AddIncomeHolderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AI_Name_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(AddIncomeHolderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AI_Amount_TF, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(AddIncomeHolderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AI_DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(AddIncomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddIncomeHolderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddIncomeHolderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddIncomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddIncomeButtonActionPerformed
        boolean isIncomeAdded = false;
        
        String name = AI_Name_TF.getText();
        Double amount = Double.parseDouble(AI_Amount_TF.getText());
        java.sql.Date date =  new java.sql.Date(AI_DateChooser.getDate().getTime());
        
        if (AI_Name_TF.getText().isEmpty() || AI_Amount_TF.getText().isEmpty() || ((JTextField)AI_DateChooser.getDateEditor().getUiComponent()).getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Some fields are empty! Please check.");
        }
        else
        {
           try
            {
                // Initializing a new stock
                Income newIncome = new Income(0, name, amount, date);
                IncomeManager incomeManager = new IncomeManager();
                isIncomeAdded = incomeManager.AddIncome(newIncome)? true: false;

                if(isIncomeAdded)
                {
                    JOptionPane.showMessageDialog(null, "New income added!");
                    this.SetFieldsEmpty();
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Error! while adding the income. Pease check again.");
                }
            }
            catch (Exception ex)
            {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            } 
        }        
    }//GEN-LAST:event_AddIncomeButtonActionPerformed

    private void AI_Name_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AI_Name_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AI_Name_TFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AI_Amount_TF;
    private com.toedter.calendar.JDateChooser AI_DateChooser;
    private javax.swing.JTextField AI_Name_TF;
    private javax.swing.JButton AddIncomeButton;
    private javax.swing.JPanel AddIncomeHolderPanel;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
