/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SalesTrack.Income;

import SalesTrack.Stock.*;
import AplicationEnums.Actions;
import Database.IncomeManager;
import Database.StockManager;
import SalesTrack.Models.Income;
import SalesTrack.Models.Stock;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author User
 */
public class ViewIncomePanel extends javax.swing.JPanel {

    
   
   /**
    * The action being made
    */
   private Actions action;
   
   private ArrayList<Income> incomes ;
   
    /**
     * Creates new form ShortTermCourse
     */
    public ViewIncomePanel() {
        initComponents();
        this.ShowAllIncomeDetails();
    }


    /**
     * Sets the table for displaying all the available incomes
     */
    public  void ShowAllIncomeDetails()
    {
        try{
            DefaultTableModel dm = (DefaultTableModel)VIP_Income_Table.getModel();
            dm.setRowCount(0);
            this.incomes = new IncomeManager().GetAllIncomesAvailable();
            if(null != incomes)
            {
                incomes.stream().forEach((stock) -> 
                {
                    dm.addRow(new Object[]
                    {
                        stock.GetID(),
                        stock.GetName(),
                        stock.GetAmount(),
                        stock.GetDate()
                     });
                });
            }
        } 
        catch (ClassNotFoundException | SQLException ex) 
        {
           JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    
    /**
     * Creates a new instance of the panel and sets the course type
     * Also identifies the action being made
     */
 /*   public ViewIncomePanel(CourseType type, Actions action) {
        initComponents();
        this.courseType = type;
        this.action = action;  
        this.FilterButtonHolder();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VIP_ItemsHolder_Panel = new javax.swing.JPanel();
        VIP_TableHolder_Panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        VIP_Income_Table = new javax.swing.JTable();
        VIP_search_TF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "View income details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Miriam Fixed", 0, 11))); // NOI18N

        VIP_ItemsHolder_Panel.setBackground(new java.awt.Color(163, 197, 204));
        VIP_ItemsHolder_Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        VIP_TableHolder_Panel.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setFont(new java.awt.Font("Miriam Fixed", 1, 11)); // NOI18N

        VIP_Income_Table.setFont(new java.awt.Font("Miriam Fixed", 0, 12)); // NOI18N
        VIP_Income_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Income ID", "Income details", "Amount", "Added date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        VIP_Income_Table.setRowHeight(28);
        VIP_Income_Table.setRowMargin(5);
        jScrollPane1.setViewportView(VIP_Income_Table);

        javax.swing.GroupLayout VIP_TableHolder_PanelLayout = new javax.swing.GroupLayout(VIP_TableHolder_Panel);
        VIP_TableHolder_Panel.setLayout(VIP_TableHolder_PanelLayout);
        VIP_TableHolder_PanelLayout.setHorizontalGroup(
            VIP_TableHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );
        VIP_TableHolder_PanelLayout.setVerticalGroup(
            VIP_TableHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VIP_TableHolder_PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        VIP_search_TF.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N
        VIP_search_TF.setMinimumSize(new java.awt.Dimension(5, 20));
        VIP_search_TF.setPreferredSize(new java.awt.Dimension(5, 20));
        VIP_search_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIP_search_TFActionPerformed(evt);
            }
        });
        VIP_search_TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                VIP_search_TFKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Miriam Fixed", 0, 12)); // NOI18N
        jLabel1.setText("Type here to search..");

        javax.swing.GroupLayout VIP_ItemsHolder_PanelLayout = new javax.swing.GroupLayout(VIP_ItemsHolder_Panel);
        VIP_ItemsHolder_Panel.setLayout(VIP_ItemsHolder_PanelLayout);
        VIP_ItemsHolder_PanelLayout.setHorizontalGroup(
            VIP_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VIP_ItemsHolder_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VIP_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VIP_TableHolder_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(VIP_ItemsHolder_PanelLayout.createSequentialGroup()
                        .addComponent(VIP_search_TF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(114, 114, 114)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        VIP_ItemsHolder_PanelLayout.setVerticalGroup(
            VIP_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VIP_ItemsHolder_PanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(VIP_TableHolder_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(VIP_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VIP_search_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VIP_ItemsHolder_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VIP_ItemsHolder_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void VIP_search_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIP_search_TFActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_VIP_search_TFActionPerformed

    private void VIP_search_TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VIP_search_TFKeyReleased
       // When search words are typed on the search textfield
        IncomeManager incomeManager = null; 
        ResultSet rs = null; 
        
        String searchedValue = VIP_search_TF.getText();
        if( searchedValue.length() > 0 )
        {
            try 
            {
                incomeManager = new IncomeManager();
                rs = incomeManager.GetIncomeDetailsOnSearching(searchedValue);
                if ( null == rs )
                {
                    
                }
                else
                {
                   VIP_Income_Table.setModel(DbUtils.resultSetToTableModel(rs));
                }
                
                // deallocation
                incomeManager.closeConection();
                incomeManager    = null;
                rs         = null;
                
            } 
            catch (ClassNotFoundException | SQLException ex) 
            {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_VIP_search_TFKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable VIP_Income_Table;
    private javax.swing.JPanel VIP_ItemsHolder_Panel;
    private javax.swing.JPanel VIP_TableHolder_Panel;
    private javax.swing.JTextField VIP_search_TF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
