/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SalesTrack.Stock;

import AplicationEnums.Actions;
import Database.StockManager;
import SalesTrack.Models.Stock;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author User
 */
public class DeleteStockPanel extends javax.swing.JPanel {

    
   
   /**
    * The action being made
    */
   private Actions action;
      
    private ArrayList<Stock> stocks ;
    
    private static String COMPANY_NAME;
    private static int COMPANY_ID;
    private static Double COMPANY_AMOUNT;
    private static Double COMPANY_AMOUNT_TO_BE_UPDATED;
    
    /**
     * 
     * Creates new form ShortTermCourse
     */
    public DeleteStockPanel() {
        initComponents();
        this.ShowAllStockDetails();
        COMPANY_NAME = null;
        COMPANY_ID = 0;
        COMPANY_AMOUNT = 0.0;
        COMPANY_AMOUNT_TO_BE_UPDATED = 0.0;
    }

    /**
     * Sets the table for displaying all the available stocks
     */
    public  void ShowAllStockDetails()
    {
        try{
            DefaultTableModel dm = (DefaultTableModel)DS_Stock_Table.getModel();
            dm.setRowCount(0);
            this.stocks = new StockManager().GetAllStocksAvailable();
            if(null != stocks)
            {
                stocks.stream().forEach((stock) -> 
                {
                    dm.addRow(new Object[]
                    {
                        stock.GetID(),
                        stock.GetName(),
                        stock.GetModelNo(),
                        stock.GetQuantity(),
                        stock.GetPricePerPiece(),
                        stock.GetTotalPrice(),
                        stock.GetDate()
                     });
                });
            }
        } 
        catch (ClassNotFoundException | SQLException ex) 
        {
           JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    /**
     * Creates a new instance of the panel and sets the course type
     * Also identifies the action being made
     */
 /*   public ViewStockPanel(CourseType type, Actions action) {
        initComponents();
        this.courseType = type;
        this.action = action;  
        this.FilterButtonHolder();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DS_ItemsHolder_Panel = new javax.swing.JPanel();
        DS_TableHolder_Panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DS_Stock_Table = new javax.swing.JTable();
        DeleteStock_Button = new javax.swing.JButton();
        DSP_search_TF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Delete stock details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Miriam Fixed", 0, 11))); // NOI18N

        DS_ItemsHolder_Panel.setBackground(new java.awt.Color(163, 197, 204));
        DS_ItemsHolder_Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        DS_TableHolder_Panel.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setFont(new java.awt.Font("Miriam Fixed", 1, 11)); // NOI18N

        DS_Stock_Table.setFont(new java.awt.Font("Miriam Fixed", 0, 12)); // NOI18N
        DS_Stock_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Stock ID", "Name of stock", "Model", "Quantity", "Price per piece", "Total price", "Added date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DS_Stock_Table.setRowHeight(28);
        DS_Stock_Table.setRowMargin(5);
        jScrollPane1.setViewportView(DS_Stock_Table);

        javax.swing.GroupLayout DS_TableHolder_PanelLayout = new javax.swing.GroupLayout(DS_TableHolder_Panel);
        DS_TableHolder_Panel.setLayout(DS_TableHolder_PanelLayout);
        DS_TableHolder_PanelLayout.setHorizontalGroup(
            DS_TableHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );
        DS_TableHolder_PanelLayout.setVerticalGroup(
            DS_TableHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DS_TableHolder_PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        DeleteStock_Button.setBackground(new java.awt.Color(255, 51, 51));
        DeleteStock_Button.setFont(new java.awt.Font("Miriam Fixed", 1, 12)); // NOI18N
        DeleteStock_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SalesTrack/Images/delete.png"))); // NOI18N
        DeleteStock_Button.setText("Delete");
        DeleteStock_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteStock_ButtonActionPerformed(evt);
            }
        });

        DSP_search_TF.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N
        DSP_search_TF.setMinimumSize(new java.awt.Dimension(5, 20));
        DSP_search_TF.setPreferredSize(new java.awt.Dimension(5, 20));
        DSP_search_TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DSP_search_TFKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Miriam Fixed", 0, 12)); // NOI18N
        jLabel1.setText("Type here to search..");

        javax.swing.GroupLayout DS_ItemsHolder_PanelLayout = new javax.swing.GroupLayout(DS_ItemsHolder_Panel);
        DS_ItemsHolder_Panel.setLayout(DS_ItemsHolder_PanelLayout);
        DS_ItemsHolder_PanelLayout.setHorizontalGroup(
            DS_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DS_ItemsHolder_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DS_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DS_TableHolder_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(DS_ItemsHolder_PanelLayout.createSequentialGroup()
                        .addComponent(DSP_search_TF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(147, 147, 147)
                        .addComponent(DeleteStock_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DS_ItemsHolder_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        DS_ItemsHolder_PanelLayout.setVerticalGroup(
            DS_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DS_ItemsHolder_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DS_TableHolder_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(DS_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DeleteStock_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DSP_search_TF, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DS_ItemsHolder_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DS_ItemsHolder_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteStock_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteStock_ButtonActionPerformed
        // Deleting a stock
        StockManager stockManager = null;
        ResultSet rs = null;
        int confirm = 0;
        boolean isDeleted = false,  isMapped = false;
        if(DS_Stock_Table.getSelectedRow() >= 0)
        {
            // Showing a confirmation dialog
            confirm = JOptionPane.showConfirmDialog(null, "Are you sure, that you want to delete the selected stock details?");
            
            if (0 == confirm)
            {
                try
                {                    
                    stockManager = new StockManager();
                    
                    // STATIC DATA POPULATION
                    COMPANY_NAME = String.valueOf(DS_Stock_Table.getValueAt(DS_Stock_Table.getSelectedRow(), 1));
                    COMPANY_ID = stockManager.GetCompanyIDForStock(COMPANY_NAME);
                    COMPANY_AMOUNT = stockManager.GetCompanyAmountForStock(COMPANY_ID);   
                    if (COMPANY_AMOUNT > 0.0)
                    {
                        COMPANY_AMOUNT_TO_BE_UPDATED = COMPANY_AMOUNT - Double.valueOf(String.valueOf(DS_Stock_Table.getValueAt(DS_Stock_Table.getSelectedRow(), 5)));
                    }                    
                    
                    isDeleted = stockManager.DeleteStockDetails(String.valueOf(DS_Stock_Table.getValueAt(DS_Stock_Table.getSelectedRow(), 0)));
                    if(isDeleted)
                    {
                        isMapped = stockManager.UpdateStockToCompanyMapAmount(COMPANY_ID, COMPANY_AMOUNT_TO_BE_UPDATED);
                        if (isMapped)
                        {
                            JOptionPane.showMessageDialog(null, "Record has been deleted...");
                            this.ShowAllStockDetails();
                        }                        
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Record could not be deleted...");
                    }   
                }
                catch (ClassNotFoundException | SQLException ex)
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, " Please select a row to continue...");
        }
    }//GEN-LAST:event_DeleteStock_ButtonActionPerformed

    private void DSP_search_TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DSP_search_TFKeyReleased
        // When search words are typed on the search textfield
        StockManager stockManager = null; 
        ResultSet rs = null; 
        
        String searchedValue = DSP_search_TF.getText();
        if( searchedValue.length() > 0 )
        {
            try 
            {
                stockManager = new StockManager();
                rs = stockManager.GetStockDetailsOnSearching(searchedValue);
                if ( null == rs )
                {
                    
                }
                else
                {
                   DS_Stock_Table.setModel(DbUtils.resultSetToTableModel(rs));
                }
                
                // deallocation
                stockManager.closeConection();
                stockManager    = null;
                rs         = null;
                
            } 
            catch (ClassNotFoundException | SQLException ex) 
            {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_DSP_search_TFKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DSP_search_TF;
    private javax.swing.JPanel DS_ItemsHolder_Panel;
    private javax.swing.JTable DS_Stock_Table;
    private javax.swing.JPanel DS_TableHolder_Panel;
    private javax.swing.JButton DeleteStock_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
