/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package SalesTrack.Login;

import Database.DataBaseManager;
import SalesTrack.Home.HomeForm;
import java.awt.Dialog;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author arun
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() throws ClassNotFoundException {
        
        initComponents();
        setLocationRelativeTo(null);
        DataBaseManager manager;
        try 
        {
            manager = new DataBaseManager();
        } catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage() );
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        Logolabel = new javax.swing.JLabel();
        jPanelLogin = new javax.swing.JPanel();
        jPanelLoginContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        UsernameTexfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        PasswordTextfield = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        CopyrightLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setResizable(false);

        jPanelMain.setBackground(new java.awt.Color(22, 37, 47));

        Logolabel.setFont(new java.awt.Font("Miriam Fixed", 0, 24)); // NOI18N
        Logolabel.setForeground(new java.awt.Color(255, 255, 255));
        Logolabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logolabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SalesTrack/Images/logo.png"))); // NOI18N
        Logolabel.setText("SalesTrack");

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logolabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(Logolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanelLogin.setBackground(new java.awt.Color(22, 37, 47));

        jPanelLoginContainer.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLoginContainer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelLoginContainer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Miriam Fixed", 0, 16)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SalesTrack/Images/username.png"))); // NOI18N
        jLabel1.setText("Username");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        UsernameTexfield.setBackground(new java.awt.Color(204, 204, 204));
        UsernameTexfield.setFont(new java.awt.Font("Miriam Fixed", 0, 16)); // NOI18N
        UsernameTexfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setFont(new java.awt.Font("Miriam Fixed", 0, 16)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SalesTrack/Images/password.png"))); // NOI18N
        jLabel2.setText("Password");

        LoginButton.setBackground(new java.awt.Color(22, 37, 47));
        LoginButton.setFont(new java.awt.Font("Miriam Fixed", 1, 16)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SalesTrack/Images/login.png"))); // NOI18N
        LoginButton.setText("Log in");
        LoginButton.setBorder(null);
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        ClearButton.setBackground(new java.awt.Color(22, 37, 47));
        ClearButton.setFont(new java.awt.Font("Miriam Fixed", 1, 16)); // NOI18N
        ClearButton.setForeground(new java.awt.Color(255, 255, 255));
        ClearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SalesTrack/Images/clear.png"))); // NOI18N
        ClearButton.setText("Clear");
        ClearButton.setBorder(null);
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        PasswordTextfield.setBackground(new java.awt.Color(204, 204, 204));
        PasswordTextfield.setFont(new java.awt.Font("Miriam Fixed", 0, 16)); // NOI18N
        PasswordTextfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PasswordTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordTextfieldKeyPressed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Miriam Fixed", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("!!!Acessing this system without the permission of administrator is prohibited!!!");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelLoginContainerLayout = new javax.swing.GroupLayout(jPanelLoginContainer);
        jPanelLoginContainer.setLayout(jPanelLoginContainerLayout);
        jPanelLoginContainerLayout.setHorizontalGroup(
            jPanelLoginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginContainerLayout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(jPanelLoginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelLoginContainerLayout.createSequentialGroup()
                        .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))
                    .addGroup(jPanelLoginContainerLayout.createSequentialGroup()
                        .addGroup(jPanelLoginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanelLoginContainerLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(22, 22, 22))
                            .addGroup(jPanelLoginContainerLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanelLoginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UsernameTexfield, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                            .addComponent(PasswordTextfield))))
                .addGap(56, 56, 56))
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        jPanelLoginContainerLayout.setVerticalGroup(
            jPanelLoginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginContainerLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanelLoginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameTexfield, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanelLoginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelLoginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LoginButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(ClearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelLogin.add(jPanelLoginContainer);

        jPanel4.setBackground(new java.awt.Color(22, 37, 47));

        CopyrightLabel.setBackground(new java.awt.Color(204, 204, 204));
        CopyrightLabel.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N
        CopyrightLabel.setForeground(new java.awt.Color(255, 255, 255));
        CopyrightLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CopyrightLabel.setText(" © VAG's solution  2017 ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(CopyrightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CopyrightLabel)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
        UsernameTexfield.setText( null );
        PasswordTextfield.setText( null );
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        try 
        {
            // creating object of database
            DataBaseManager dbManager = new DataBaseManager();            
            boolean isValid = false;
            
            // Data from testboxes
            if( UsernameTexfield.getText().length() < 25 &&
                PasswordTextfield.getPassword().length < 25 )
            {
                // Checking the vaidity of the user
                isValid = dbManager.IsUserValid(UsernameTexfield.getText(), 
                                        new String( PasswordTextfield.getPassword() ));
                
                if(!isValid)
                {
                   JOptionPane.showMessageDialog(rootPane, "Please check your login credentials ..");
                }
                else
                {
                    HomeForm home = new HomeForm();
                    home.setVisible(true);                   
                    this.hide();
                }
            }
            else
            {
                JOptionPane.showMessageDialog( rootPane, " Username or Password too long!" );
            }
                    
                   
                    
        }
        catch( ClassNotFoundException | SQLException ex )
        {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage() );
        }           
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void PasswordTextfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordTextfieldKeyPressed
        // Handling login by hitting Enter key
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
        {  
            try 
            {
                // creating object of database
                DataBaseManager dbManager = new DataBaseManager();            
                Dimension screenSize      = Toolkit.getDefaultToolkit().getScreenSize();
                boolean isValid = false;

                // Data from testboxes
                if( UsernameTexfield.getText().length() < 25 &&
                    PasswordTextfield.getPassword().length < 25 )
                {
                    // Checking the vaidity of the user
                    isValid = dbManager.IsUserValid(UsernameTexfield.getText(), 
                                            new String( PasswordTextfield.getPassword() ));

                    if(!isValid)
                    {
                       JOptionPane.showMessageDialog(rootPane, "Please check your login credentials ..");
                    }
                    else
                    {
                        HomeForm home = new HomeForm();
                        home.setVisible(true);                   
                        this.hide();
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog( rootPane, " Username or Password too long!" );
                }



            }
            catch( ClassNotFoundException | SQLException ex )
            {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage() );
            }
        }
    }//GEN-LAST:event_PasswordTextfieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearButton;
    private javax.swing.JLabel CopyrightLabel;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel Logolabel;
    private javax.swing.JPasswordField PasswordTextfield;
    private javax.swing.JTextField UsernameTexfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPanel jPanelLoginContainer;
    private javax.swing.JPanel jPanelMain;
    // End of variables declaration//GEN-END:variables
}
