/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SalesTrack.Credit;

import SalesTrack.Stock.*;
import AplicationEnums.Actions;
import Database.CreditManager;
import Database.ExpenseManager;
import Database.StockManager;
import SalesTrack.Models.Credit;
import SalesTrack.Models.Expense;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author User
 */
public class DeleteCreditPanel extends javax.swing.JPanel {

    
   
   /**
    * The action being made
    */
   private Actions action;
   
   private ArrayList<Credit> credits ;
   
    private static String COMPANY_NAME;
    private static int COMPANY_ID;
    private static Double COMPANY_AMOUNT;
    private static Double COMPANY_AMOUNT_TO_BE_UPDATED;
   
    /**
     * Creates new form ShortTermCourse
     */
    public DeleteCreditPanel() {
        initComponents();
        this.ShowAllCreditDetails();
        COMPANY_NAME = null;
        COMPANY_ID = 0;
        COMPANY_AMOUNT = 0.0;
        COMPANY_AMOUNT_TO_BE_UPDATED = 0.0;
    }

    /**
     * Sets the table for displaying all the available incomes
     */
    public  void ShowAllCreditDetails()
    {
        try{
            DefaultTableModel dm = (DefaultTableModel)DCP_Credit_Table.getModel();
            dm.setRowCount(0);
            this.credits = new CreditManager().GetAllCreditsAvailable();
            if(null != credits)
            {
                credits.stream().forEach((stock) -> 
                {
                    dm.addRow(new Object[]
                    {
                        stock.GetID(),
                        stock.GetCompanyID(),
                        stock.GetCompanyName(),
                        stock.GetAmount(),
                        stock.GetDate(),
                        stock.GetStatus()
                     });
                });
            }
        } 
        catch (ClassNotFoundException | SQLException ex) 
        {
           JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    /**
     * Creates a new instance of the panel and sets the course type
     * Also identifies the action being made
     */
 /*   public ViewStockPanel(CourseType type, Actions action) {
        initComponents();
        this.courseType = type;
        this.action = action;  
        this.FilterButtonHolder();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DCP_ItemsHolder_Panel = new javax.swing.JPanel();
        DCP_TableHolder_Panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DCP_Credit_Table = new javax.swing.JTable();
        DeleteCredit_Button = new javax.swing.JButton();
        DCP_search_TF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Delete credit details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Miriam Fixed", 0, 11))); // NOI18N

        DCP_ItemsHolder_Panel.setBackground(new java.awt.Color(163, 197, 204));
        DCP_ItemsHolder_Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        DCP_TableHolder_Panel.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setFont(new java.awt.Font("Miriam Fixed", 1, 11)); // NOI18N

        DCP_Credit_Table.setFont(new java.awt.Font("Miriam Fixed", 0, 12)); // NOI18N
        DCP_Credit_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Credit ID", "Stock ID", "Stock name", "Amount", "Credited date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DCP_Credit_Table.setRowHeight(28);
        DCP_Credit_Table.setRowMargin(5);
        jScrollPane1.setViewportView(DCP_Credit_Table);

        javax.swing.GroupLayout DCP_TableHolder_PanelLayout = new javax.swing.GroupLayout(DCP_TableHolder_Panel);
        DCP_TableHolder_Panel.setLayout(DCP_TableHolder_PanelLayout);
        DCP_TableHolder_PanelLayout.setHorizontalGroup(
            DCP_TableHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );
        DCP_TableHolder_PanelLayout.setVerticalGroup(
            DCP_TableHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DCP_TableHolder_PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        DeleteCredit_Button.setBackground(new java.awt.Color(255, 51, 51));
        DeleteCredit_Button.setFont(new java.awt.Font("Miriam Fixed", 1, 12)); // NOI18N
        DeleteCredit_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SalesTrack/Images/delete.png"))); // NOI18N
        DeleteCredit_Button.setText("Delete credit");
        DeleteCredit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteCredit_ButtonActionPerformed(evt);
            }
        });

        DCP_search_TF.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N
        DCP_search_TF.setMinimumSize(new java.awt.Dimension(5, 20));
        DCP_search_TF.setPreferredSize(new java.awt.Dimension(5, 20));
        DCP_search_TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DCP_search_TFKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Miriam Fixed", 0, 12)); // NOI18N
        jLabel1.setText("Type here to search..");

        javax.swing.GroupLayout DCP_ItemsHolder_PanelLayout = new javax.swing.GroupLayout(DCP_ItemsHolder_Panel);
        DCP_ItemsHolder_Panel.setLayout(DCP_ItemsHolder_PanelLayout);
        DCP_ItemsHolder_PanelLayout.setHorizontalGroup(
            DCP_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DCP_ItemsHolder_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DCP_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DCP_TableHolder_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(DCP_ItemsHolder_PanelLayout.createSequentialGroup()
                        .addComponent(DCP_search_TF, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                        .addGap(127, 127, 127)
                        .addComponent(DeleteCredit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DCP_ItemsHolder_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        DCP_ItemsHolder_PanelLayout.setVerticalGroup(
            DCP_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DCP_ItemsHolder_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DCP_TableHolder_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DCP_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DeleteCredit_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DCP_search_TF, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DCP_ItemsHolder_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DCP_ItemsHolder_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteCredit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteCredit_ButtonActionPerformed
        // Deleting a credit
        CreditManager creditManager = null;
        ResultSet rs = null;
        int confirm = 0;
        boolean isDeleted = false, isMapped = false;
        if(DCP_Credit_Table.getSelectedRow() >= 0)
        {
            // Showing a confirmation dialog            
            if (0 == confirm)
            {
                try
                {
                    confirm = JOptionPane.showConfirmDialog(null, "Are you sure, that you want to delete the selected credit details?");  
                    
                    // STATIC DATA POPULATION
                    COMPANY_ID = Integer.parseInt(String.valueOf(DCP_Credit_Table.getValueAt(DCP_Credit_Table.getSelectedRow(), 1)));
                    COMPANY_NAME = String.valueOf(DCP_Credit_Table.getValueAt(DCP_Credit_Table.getSelectedRow(), 2));
                    StockManager manager = new StockManager();
                    COMPANY_AMOUNT = manager.GetCompanyAmountForStock(COMPANY_ID);                    
                    COMPANY_AMOUNT_TO_BE_UPDATED = COMPANY_AMOUNT + Double.valueOf(String.valueOf(DCP_Credit_Table.getValueAt(DCP_Credit_Table.getSelectedRow(), 3)));
                            
                    creditManager = new CreditManager();
                    isDeleted = creditManager.DeleteCreditDetails(String.valueOf(DCP_Credit_Table.getValueAt(DCP_Credit_Table.getSelectedRow(), 0)));
                    if(isDeleted)
                    {
                        isMapped = manager.UpdateStockToCompanyMapAmount(COMPANY_ID, COMPANY_AMOUNT_TO_BE_UPDATED);
                        if (isMapped)
                        {
                            JOptionPane.showMessageDialog(null, "Record has been deleted...");
                            this.ShowAllCreditDetails();
                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Record could not be deleted...");
                    }   
                }
                catch (ClassNotFoundException | SQLException ex)
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, " Please select a row to continue...");
        }
    }//GEN-LAST:event_DeleteCredit_ButtonActionPerformed

    private void DCP_search_TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DCP_search_TFKeyReleased
        // When search words are typed on the search textfield
        CreditManager creditManager = null; 
        ResultSet rs = null; 
        
        String searchedValue = DCP_search_TF.getText();
        if( searchedValue.length() > 0 )
        {
            try 
            {
                creditManager = new CreditManager();
                rs = creditManager.GetCreditDetailsOnSearching(searchedValue);
                if ( null == rs )
                {
                    
                }
                else
                {
                   DCP_Credit_Table.setModel(DbUtils.resultSetToTableModel(rs));
                }
                
                // deallocation
                creditManager.closeConection();
                creditManager    = null;
                rs         = null;
                
            } 
            catch (ClassNotFoundException | SQLException ex) 
            {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_DCP_search_TFKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DCP_Credit_Table;
    private javax.swing.JPanel DCP_ItemsHolder_Panel;
    private javax.swing.JPanel DCP_TableHolder_Panel;
    private javax.swing.JTextField DCP_search_TF;
    private javax.swing.JButton DeleteCredit_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
