/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SalesTrack.Credit;
import Database.CreditManager;
import Database.ExpenseManager;
import Database.StockManager;
import SalesTrack.Models.Credit;
import SalesTrack.Models.Expense;
import SalesTrack.Stock.*;
import java.awt.Frame;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author User
 */
public class UpdateCreditPanel extends javax.swing.JPanel {
    
    private static String COMPANY_NAME;
    private static int COMPANY_ID;
    private static Double COMPANY_AMOUNT;
    private static Double AMOUNT_BEFORE_UPDATE;
    private static Double COMPANY_AMOUNT_TO_BE_UPDATED;
    
    /**
     * Creates new form 
     */
    public UpdateCreditPanel() {
        initComponents();
        COMPANY_NAME = null;
        COMPANY_ID = 0;
        COMPANY_AMOUNT = 0.0;
        AMOUNT_BEFORE_UPDATE = 0.0;
        COMPANY_AMOUNT_TO_BE_UPDATED = 0.0;
    }

    public void PopulateCreditDetails()
    {
       CreditManager manager = null; 
        ResultSet rs = null; 
        try 
            {
                manager = new CreditManager();
                rs = manager.GetAllCredits();
                if ( null == rs )
                {
                    
                }
                else
                {
                   ChooserDialogTable.setModel(DbUtils.resultSetToTableModel(rs));
                }
                
                // deallocation
                manager.closeConection();
                manager    = null;
                rs         = null;
                
            } 
            catch (ClassNotFoundException | SQLException ex) 
            {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }       
    } 
    
    private void SetFieldsEmpty()
    {
        UCP_CreditID_TF.setText(null);
        UCP_StockID_TF.setText(null);
        UCP_Name_TF.setText(null);
        UCP_Amount_TF.setText(null);
        ((JTextField)UCP_DateChooser.getDateEditor().getUiComponent()).setText(null);
    }
    
    private boolean IsAmountUpdateNeeded(Double amount)
    {
        if (AMOUNT_BEFORE_UPDATE == amount)
        {
            return false;
        }
        else
        {
            Double stepValue = amount - AMOUNT_BEFORE_UPDATE;
            COMPANY_AMOUNT_TO_BE_UPDATED = COMPANY_AMOUNT - stepValue;
            return true;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChooserDialog = new javax.swing.JDialog();
        ChosserDialogBasePanel = new javax.swing.JPanel();
        ChooserDialogTextBox = new javax.swing.JTextField();
        ChooserDialogScrollPane = new javax.swing.JScrollPane();
        ChooserDialogTable = new javax.swing.JTable();
        ChooserDialogOKButton = new javax.swing.JButton();
        ChooserDialogCloseButton = new javax.swing.JButton();
        SubjectChooserLabel = new javax.swing.JLabel();
        UCP_ItemsHolder_Panel = new javax.swing.JPanel();
        UCP_CreditID_TF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        UCP_StockID_TF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        UCP_UpdateCredit_Button = new javax.swing.JButton();
        UCP_Amount_TF = new javax.swing.JTextField();
        UCP_Name_TF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        UCP_DateChooser = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        UCP_Status_CB = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        ChosserDialogBasePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Miriam Fixed", 0, 12))); // NOI18N

        ChooserDialogTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ChooserDialogTextBoxKeyReleased(evt);
            }
        });

        ChooserDialogTable.setFont(new java.awt.Font("Miriam Fixed", 0, 12)); // NOI18N
        ChooserDialogTable.setForeground(new java.awt.Color(102, 0, 0));
        ChooserDialogTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        ChooserDialogScrollPane.setViewportView(ChooserDialogTable);

        ChooserDialogOKButton.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N
        ChooserDialogOKButton.setText("OK");
        ChooserDialogOKButton.setBorder(null);
        ChooserDialogOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooserDialogOKButtonActionPerformed(evt);
            }
        });

        ChooserDialogCloseButton.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N
        ChooserDialogCloseButton.setText("CLOSE");
        ChooserDialogCloseButton.setBorder(null);
        ChooserDialogCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooserDialogCloseButtonActionPerformed(evt);
            }
        });

        SubjectChooserLabel.setFont(new java.awt.Font("Miriam Fixed", 0, 12)); // NOI18N
        SubjectChooserLabel.setText("Enter here to search");

        javax.swing.GroupLayout ChosserDialogBasePanelLayout = new javax.swing.GroupLayout(ChosserDialogBasePanel);
        ChosserDialogBasePanel.setLayout(ChosserDialogBasePanelLayout);
        ChosserDialogBasePanelLayout.setHorizontalGroup(
            ChosserDialogBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChosserDialogBasePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(SubjectChooserLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ChosserDialogBasePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ChosserDialogBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChooserDialogTextBox)
                    .addComponent(ChooserDialogScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChosserDialogBasePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ChooserDialogOKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ChooserDialogCloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ChosserDialogBasePanelLayout.setVerticalGroup(
            ChosserDialogBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChosserDialogBasePanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(SubjectChooserLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ChooserDialogTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ChooserDialogScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(ChosserDialogBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ChooserDialogOKButton, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(ChooserDialogCloseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout ChooserDialogLayout = new javax.swing.GroupLayout(ChooserDialog.getContentPane());
        ChooserDialog.getContentPane().setLayout(ChooserDialogLayout);
        ChooserDialogLayout.setHorizontalGroup(
            ChooserDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ChosserDialogBasePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        ChooserDialogLayout.setVerticalGroup(
            ChooserDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ChosserDialogBasePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Update credit details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Miriam Fixed", 0, 11))); // NOI18N

        UCP_ItemsHolder_Panel.setBackground(new java.awt.Color(204, 219, 222));
        UCP_ItemsHolder_Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        UCP_CreditID_TF.setEditable(false);
        UCP_CreditID_TF.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N
        UCP_CreditID_TF.setEnabled(false);
        UCP_CreditID_TF.setMinimumSize(new java.awt.Dimension(5, 20));
        UCP_CreditID_TF.setPreferredSize(new java.awt.Dimension(5, 20));
        UCP_CreditID_TF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UCP_CreditID_TFMouseClicked(evt);
            }
        });
        UCP_CreditID_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UCP_CreditID_TFActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N
        jLabel2.setText("Company ID");

        UCP_StockID_TF.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N
        UCP_StockID_TF.setMinimumSize(new java.awt.Dimension(5, 20));
        UCP_StockID_TF.setPreferredSize(new java.awt.Dimension(5, 20));

        jLabel3.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N
        jLabel3.setText("Amount");

        jLabel19.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N
        jLabel19.setText("Date");

        UCP_UpdateCredit_Button.setBackground(new java.awt.Color(0, 102, 255));
        UCP_UpdateCredit_Button.setFont(new java.awt.Font("Miriam Fixed", 1, 14)); // NOI18N
        UCP_UpdateCredit_Button.setForeground(new java.awt.Color(255, 255, 255));
        UCP_UpdateCredit_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SalesTrack/Images/update.png"))); // NOI18N
        UCP_UpdateCredit_Button.setText("Update credit");
        UCP_UpdateCredit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UCP_UpdateCredit_ButtonActionPerformed(evt);
            }
        });

        UCP_Amount_TF.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N
        UCP_Amount_TF.setMinimumSize(new java.awt.Dimension(5, 20));
        UCP_Amount_TF.setPreferredSize(new java.awt.Dimension(5, 20));

        UCP_Name_TF.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N
        UCP_Name_TF.setMinimumSize(new java.awt.Dimension(5, 20));
        UCP_Name_TF.setPreferredSize(new java.awt.Dimension(5, 20));

        jLabel4.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N
        jLabel4.setText("Name");

        jLabel5.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N
        jLabel5.setText("Click here ");

        jLabel6.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N
        jLabel6.setText("Status");

        UCP_Status_CB.setFont(new java.awt.Font("Miriam Fixed", 0, 12)); // NOI18N
        UCP_Status_CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CLOSED", "OPEN" }));

        jLabel7.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N
        jLabel7.setText("to select");

        javax.swing.GroupLayout UCP_ItemsHolder_PanelLayout = new javax.swing.GroupLayout(UCP_ItemsHolder_Panel);
        UCP_ItemsHolder_Panel.setLayout(UCP_ItemsHolder_PanelLayout);
        UCP_ItemsHolder_PanelLayout.setHorizontalGroup(
            UCP_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UCP_ItemsHolder_PanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(UCP_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(UCP_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(UCP_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UCP_DateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UCP_Amount_TF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UCP_Name_TF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UCP_StockID_TF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UCP_CreditID_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UCP_UpdateCredit_Button)
                    .addComponent(UCP_Status_CB, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(144, 144, 144))
        );
        UCP_ItemsHolder_PanelLayout.setVerticalGroup(
            UCP_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UCP_ItemsHolder_PanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(UCP_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UCP_CreditID_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(UCP_ItemsHolder_PanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(UCP_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UCP_StockID_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(UCP_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UCP_Name_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(UCP_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UCP_Amount_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(UCP_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UCP_DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(UCP_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UCP_Status_CB, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(UCP_UpdateCredit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UCP_ItemsHolder_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UCP_ItemsHolder_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UCP_UpdateCredit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UCP_UpdateCredit_ButtonActionPerformed
        boolean isCreditUpdated = false;
        boolean isCompanyMapped = false;
        int creditID = Integer.parseInt(UCP_CreditID_TF.getText());
        int stockID = Integer.parseInt(UCP_StockID_TF.getText());
        String name = UCP_Name_TF.getText();
        Double amount = Double.parseDouble(UCP_Amount_TF.getText());
        String dateText = ((JTextField)UCP_DateChooser.getDateEditor().getUiComponent()).getText();
        java.sql.Date date =  new java.sql.Date(UCP_DateChooser.getDate().getTime());
        String status = UCP_Status_CB.getSelectedItem().toString();
        
        if(UCP_CreditID_TF.getText().isEmpty() || UCP_StockID_TF.getText().isEmpty() || UCP_Name_TF.getText().isEmpty() || dateText.isEmpty()
                || UCP_Amount_TF.getText().isEmpty())
        {
               JOptionPane.showMessageDialog(null, "Cannot update with empty fields!");
        }
        else
        {
            try                    
            {
                StockManager stockManager = new StockManager();
                
                // Initializing a new expense
                Credit newCredit = new Credit(creditID, stockID, name, amount, date, status);
                CreditManager creditManager = new CreditManager();
                isCreditUpdated = creditManager.UpdateCredit(newCredit)? true: false;
                
                if (this.IsAmountUpdateNeeded(amount))
                {
                    
                    isCompanyMapped= stockManager.UpdateStockToCompanyMapAmount(COMPANY_ID, COMPANY_AMOUNT_TO_BE_UPDATED);
                        
                }

                if(isCreditUpdated)
                {
                    if(isCompanyMapped)
                    {
                        JOptionPane.showMessageDialog(null, "Credit and comapny details have been updated!");
                        this.SetFieldsEmpty();
                    }
                    else                        
                    {
                        JOptionPane.showMessageDialog(null, "Credit has been updated!");
                        this.SetFieldsEmpty();
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Error! while updating the credit. Pease check again.");
                }
            }
            catch (Exception ex)
            {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }          
                 
        }
    }//GEN-LAST:event_UCP_UpdateCredit_ButtonActionPerformed

    private void UCP_CreditID_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UCP_CreditID_TFActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_UCP_CreditID_TFActionPerformed

    private void ChooserDialogTextBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ChooserDialogTextBoxKeyReleased
        // When searched for
        CreditManager manager = null;
        ResultSet rs = null;
        String searchWord = ChooserDialogTextBox.getText();
        if(searchWord .length() > 0)
        {
            try {
                manager = new CreditManager();
                rs = manager.GetCreditDetailsOnSearching(searchWord);
                if ( null == rs )
                {

                }
                else
                {
                    ChooserDialogTable.setModel( DbUtils.resultSetToTableModel(rs));
                }

                // deallocation
                manager.closeConection();
                manager    = null;
                rs         = null;

            }
            catch (ClassNotFoundException | SQLException ex)
            {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_ChooserDialogTextBoxKeyReleased

    private void ChooserDialogOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooserDialogOKButtonActionPerformed
        // On clicking the Ok button
        if( ChooserDialogTable.getSelectedRow() >= 0)
        {
            // Set text field
            UCP_CreditID_TF.setText(String.valueOf(ChooserDialogTable.getValueAt( ChooserDialogTable.getSelectedRow() ,0)));
            UCP_StockID_TF.setText(String.valueOf(ChooserDialogTable.getValueAt( ChooserDialogTable.getSelectedRow() ,1)));
            
            // STATIC DATA POPULATION
            COMPANY_ID = Integer.parseInt(String.valueOf(ChooserDialogTable.getValueAt( ChooserDialogTable.getSelectedRow() ,1)));
            
            UCP_Name_TF.setText(String.valueOf(ChooserDialogTable.getValueAt( ChooserDialogTable.getSelectedRow() ,2)));   
            
            // STATIC DATA POPULATION
            COMPANY_NAME = String.valueOf(ChooserDialogTable.getValueAt( ChooserDialogTable.getSelectedRow() ,3));
            
            try
            {
                // Instantly saving the company ID and amount locally from the stock to company mapping info in DB
                // This is required to identify whether the company name is getting upadetd for an already mapped company
                StockManager manager = new StockManager();
                COMPANY_AMOUNT = manager.GetCompanyAmountForStock(COMPANY_ID);
                manager = null;
            }
            catch (Exception ex)
            {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            
            UCP_Amount_TF.setText(String.valueOf(ChooserDialogTable.getValueAt( ChooserDialogTable.getSelectedRow() ,3)));
            
            // STATIC DATA POPULATION
            AMOUNT_BEFORE_UPDATE = Double.valueOf(String.valueOf(ChooserDialogTable.getValueAt( ChooserDialogTable.getSelectedRow() ,3)));
            
            ((JTextField)UCP_DateChooser.getDateEditor().getUiComponent()).setText(String.valueOf(ChooserDialogTable.getValueAt( ChooserDialogTable.getSelectedRow() ,4)));
            UCP_Status_CB.setSelectedItem(String.valueOf(ChooserDialogTable.getValueAt( ChooserDialogTable.getSelectedRow() ,5)));
            
            // dispose the search dialog
            ChooserDialog.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please select a row to continue...");
        }
    }//GEN-LAST:event_ChooserDialogOKButtonActionPerformed

    private void ChooserDialogCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooserDialogCloseButtonActionPerformed
        // Disposing search dialog
        ChooserDialog.dispose();
    }//GEN-LAST:event_ChooserDialogCloseButtonActionPerformed

    private void UCP_CreditID_TFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UCP_CreditID_TFMouseClicked
        ChooserDialog.setSize(800, 500);
        ChooserDialog.setLocationRelativeTo(this);
        ChooserDialog.setVisible(true);
        this.PopulateCreditDetails(); 
    }//GEN-LAST:event_UCP_CreditID_TFMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog ChooserDialog;
    private javax.swing.JButton ChooserDialogCloseButton;
    private javax.swing.JButton ChooserDialogOKButton;
    private javax.swing.JScrollPane ChooserDialogScrollPane;
    private javax.swing.JTable ChooserDialogTable;
    private javax.swing.JTextField ChooserDialogTextBox;
    private javax.swing.JPanel ChosserDialogBasePanel;
    private javax.swing.JLabel SubjectChooserLabel;
    private javax.swing.JTextField UCP_Amount_TF;
    private javax.swing.JTextField UCP_CreditID_TF;
    private com.toedter.calendar.JDateChooser UCP_DateChooser;
    private javax.swing.JPanel UCP_ItemsHolder_Panel;
    private javax.swing.JTextField UCP_Name_TF;
    private javax.swing.JComboBox<String> UCP_Status_CB;
    private javax.swing.JTextField UCP_StockID_TF;
    private javax.swing.JButton UCP_UpdateCredit_Button;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables


}
