/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SalesTrack.Credit;

import SalesTrack.Stock.*;
import AplicationEnums.Actions;
import Database.CreditManager;
import Database.ExpenseManager;
import SalesTrack.Models.Credit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author User
 */
public class ViewCreditPanel extends javax.swing.JPanel {

    
   
   /**
    * The action being made
    */
   private Actions action;
   
   private ArrayList<Credit> credits ;
    /**
     * Creates new form ShortTermCourse
     */
    public ViewCreditPanel() {
        initComponents();
        this.ShowAllCreditDetails();
    }

    /**
     * Sets the table for displaying all the available expenses
     */
    public  void ShowAllCreditDetails()
    {
        try{
            DefaultTableModel dm = (DefaultTableModel)VCP_Credit_Table.getModel();
            dm.setRowCount(0);
            this.credits = new CreditManager().GetAllCreditsAvailable();
            if(null != credits)
            {
                credits.stream().forEach((stock) -> 
                {
                    dm.addRow(new Object[]
                    {
                        stock.GetID(),
                        stock.GetCompanyID(),
                        stock.GetCompanyName(),
                        stock.GetAmount(),
                        stock.GetDate(),
                        stock.GetStatus()
                     });
                });
            }
        } 
        catch (ClassNotFoundException | SQLException ex) 
        {
           JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    
    /**
     * Creates a new instance of the panel and sets the course type
     * Also identifies the action being made
     */
 /*   public ViewCreditPanel(CourseType type, Actions action) {
        initComponents();
        this.courseType = type;
        this.action = action;  
        this.FilterButtonHolder();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VCP_ItemsHolder_Panel = new javax.swing.JPanel();
        VCP_TableHolder_Panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        VCP_Credit_Table = new javax.swing.JTable();
        VCP_search_TF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "View credit details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Miriam Fixed", 0, 11))); // NOI18N

        VCP_ItemsHolder_Panel.setBackground(new java.awt.Color(163, 197, 204));
        VCP_ItemsHolder_Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        VCP_TableHolder_Panel.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setFont(new java.awt.Font("Miriam Fixed", 1, 11)); // NOI18N

        VCP_Credit_Table.setFont(new java.awt.Font("Miriam Fixed", 0, 12)); // NOI18N
        VCP_Credit_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Credit ID", "Company ID", "Company Name", "Amount", "Credited date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        VCP_Credit_Table.setRowHeight(28);
        VCP_Credit_Table.setRowMargin(5);
        jScrollPane1.setViewportView(VCP_Credit_Table);

        javax.swing.GroupLayout VCP_TableHolder_PanelLayout = new javax.swing.GroupLayout(VCP_TableHolder_Panel);
        VCP_TableHolder_Panel.setLayout(VCP_TableHolder_PanelLayout);
        VCP_TableHolder_PanelLayout.setHorizontalGroup(
            VCP_TableHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );
        VCP_TableHolder_PanelLayout.setVerticalGroup(
            VCP_TableHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VCP_TableHolder_PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        VCP_search_TF.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N
        VCP_search_TF.setMinimumSize(new java.awt.Dimension(5, 20));
        VCP_search_TF.setPreferredSize(new java.awt.Dimension(5, 20));
        VCP_search_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VCP_search_TFActionPerformed(evt);
            }
        });
        VCP_search_TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                VCP_search_TFKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Miriam Fixed", 0, 12)); // NOI18N
        jLabel1.setText("Type here to search..");

        javax.swing.GroupLayout VCP_ItemsHolder_PanelLayout = new javax.swing.GroupLayout(VCP_ItemsHolder_Panel);
        VCP_ItemsHolder_Panel.setLayout(VCP_ItemsHolder_PanelLayout);
        VCP_ItemsHolder_PanelLayout.setHorizontalGroup(
            VCP_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VCP_ItemsHolder_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VCP_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VCP_TableHolder_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(VCP_ItemsHolder_PanelLayout.createSequentialGroup()
                        .addComponent(VCP_search_TF, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                        .addGap(82, 82, 82)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        VCP_ItemsHolder_PanelLayout.setVerticalGroup(
            VCP_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VCP_ItemsHolder_PanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(VCP_TableHolder_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(VCP_ItemsHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VCP_search_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VCP_ItemsHolder_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VCP_ItemsHolder_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void VCP_search_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VCP_search_TFActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_VCP_search_TFActionPerformed

    private void VCP_search_TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VCP_search_TFKeyReleased
        // When search words are typed on the search textfield
        CreditManager creditManager = null; 
        ResultSet rs = null; 
        
        String searchedValue = VCP_search_TF.getText();
        if( searchedValue.length() > 0 )
        {
            try 
            {
                creditManager = new CreditManager();
                rs = creditManager.GetCreditDetailsOnSearching(searchedValue);
                if ( null == rs )
                {
                    
                }
                else
                {
                   VCP_Credit_Table.setModel(DbUtils.resultSetToTableModel(rs));
                }
                
                // deallocation
                creditManager.closeConection();
                creditManager    = null;
                rs         = null;
                
            } 
            catch (ClassNotFoundException | SQLException ex) 
            {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_VCP_search_TFKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable VCP_Credit_Table;
    private javax.swing.JPanel VCP_ItemsHolder_Panel;
    private javax.swing.JPanel VCP_TableHolder_Panel;
    private javax.swing.JTextField VCP_search_TF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
