/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SalesTrack.Home;
import SalesTrack.Login.LoginForm;
import SalesTrack.Action.ActionPanel;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import AplicationEnums.Functionality;
import SalesTrack.Action.SummaryActionPanel;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author User
 */
public class HomePanel extends javax.swing.JPanel {

    /**
     * Creates new form HomePanelNew
     */
    public HomePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderPanel = new javax.swing.JPanel();
        HeaderLogoLabel = new javax.swing.JLabel();
        InfoLabelHeader2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        LogoLabel = new javax.swing.JLabel();
        SideOptionsPanel = new javax.swing.JPanel();
        RegularOptionsPanel = new javax.swing.JPanel();
        HomeOptionButton = new javax.swing.JButton();
        StockOptionButton = new javax.swing.JButton();
        SalesOptionButton = new javax.swing.JButton();
        IncomeOptionButton = new javax.swing.JButton();
        ExpenseOptionButton = new javax.swing.JButton();
        CreditOptionButton = new javax.swing.JButton();
        OtherOptionsPanel1 = new javax.swing.JPanel();
        LogoutButton = new javax.swing.JButton();
        ChangePasswordButton = new javax.swing.JButton();
        SummaryOptionButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        MiddlePanel = new javax.swing.JPanel();
        SubHomePanel = new javax.swing.JPanel();
        AdminHomeLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        FooterLabel = new javax.swing.JLabel();

        HeaderPanel.setBackground(new java.awt.Color(22, 37, 47));
        HeaderPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        HeaderLogoLabel.setFont(new java.awt.Font("Miriam Fixed", 1, 24)); // NOI18N
        HeaderLogoLabel.setForeground(new java.awt.Color(255, 255, 255));
        HeaderLogoLabel.setText("SalesTrack");

        InfoLabelHeader2.setFont(new java.awt.Font("Miriam Fixed", 0, 12)); // NOI18N
        InfoLabelHeader2.setForeground(new java.awt.Color(204, 219, 222));
        InfoLabelHeader2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        InfoLabelHeader2.setText("Assists you in tracking sales activities in a shop.");

        jToggleButton1.setSelected(true);
        jToggleButton1.setText("< >");
        jToggleButton1.setBorder(null);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        LogoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SalesTrack/Images/logo.png"))); // NOI18N

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(LogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HeaderPanelLayout.createSequentialGroup()
                        .addGroup(HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InfoLabelHeader2)
                            .addComponent(HeaderLogoLabel))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(HeaderLogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(InfoLabelHeader2, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addGap(23, 23, 23))
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addComponent(LogoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        SideOptionsPanel.setBackground(new java.awt.Color(22, 37, 47));
        SideOptionsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        RegularOptionsPanel.setBackground(new java.awt.Color(22, 37, 47));
        RegularOptionsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Regular options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Miriam Fixed", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        RegularOptionsPanel.setLayout(new java.awt.GridLayout(6, 1));

        HomeOptionButton.setBackground(new java.awt.Color(22, 37, 47));
        HomeOptionButton.setFont(new java.awt.Font("Miriam Fixed", 1, 16)); // NOI18N
        HomeOptionButton.setForeground(new java.awt.Color(255, 255, 255));
        HomeOptionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SalesTrack/Images/home.png"))); // NOI18N
        HomeOptionButton.setText("Home");
        HomeOptionButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        HomeOptionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeOptionButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeOptionButtonMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                HomeOptionButtonMouseReleased(evt);
            }
        });
        HomeOptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeOptionButtonActionPerformed(evt);
            }
        });
        RegularOptionsPanel.add(HomeOptionButton);

        StockOptionButton.setBackground(new java.awt.Color(22, 37, 47));
        StockOptionButton.setFont(new java.awt.Font("Miriam Fixed", 1, 15)); // NOI18N
        StockOptionButton.setForeground(new java.awt.Color(255, 255, 255));
        StockOptionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SalesTrack/Images/stock.png"))); // NOI18N
        StockOptionButton.setText("Stock");
        StockOptionButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        StockOptionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StockOptionButtonMouseClicked(evt);
            }
        });
        StockOptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockOptionButtonActionPerformed(evt);
            }
        });
        RegularOptionsPanel.add(StockOptionButton);

        SalesOptionButton.setBackground(new java.awt.Color(22, 37, 47));
        SalesOptionButton.setFont(new java.awt.Font("Miriam Fixed", 1, 15)); // NOI18N
        SalesOptionButton.setForeground(new java.awt.Color(255, 255, 255));
        SalesOptionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SalesTrack/Images/sales.png"))); // NOI18N
        SalesOptionButton.setText("Sales");
        SalesOptionButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SalesOptionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalesOptionButtonMouseClicked(evt);
            }
        });
        SalesOptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalesOptionButtonActionPerformed(evt);
            }
        });
        RegularOptionsPanel.add(SalesOptionButton);

        IncomeOptionButton.setBackground(new java.awt.Color(22, 37, 47));
        IncomeOptionButton.setFont(new java.awt.Font("Miriam Fixed", 1, 15)); // NOI18N
        IncomeOptionButton.setForeground(new java.awt.Color(255, 255, 255));
        IncomeOptionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SalesTrack/Images/income.png"))); // NOI18N
        IncomeOptionButton.setText("Income");
        IncomeOptionButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        IncomeOptionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IncomeOptionButtonMouseClicked(evt);
            }
        });
        IncomeOptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncomeOptionButtonActionPerformed(evt);
            }
        });
        RegularOptionsPanel.add(IncomeOptionButton);

        ExpenseOptionButton.setBackground(new java.awt.Color(22, 37, 47));
        ExpenseOptionButton.setFont(new java.awt.Font("Miriam Fixed", 1, 15)); // NOI18N
        ExpenseOptionButton.setForeground(new java.awt.Color(255, 255, 255));
        ExpenseOptionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SalesTrack/Images/expense.png"))); // NOI18N
        ExpenseOptionButton.setText("Expense");
        ExpenseOptionButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ExpenseOptionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExpenseOptionButtonMouseClicked(evt);
            }
        });
        ExpenseOptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpenseOptionButtonActionPerformed(evt);
            }
        });
        RegularOptionsPanel.add(ExpenseOptionButton);

        CreditOptionButton.setBackground(new java.awt.Color(22, 37, 47));
        CreditOptionButton.setFont(new java.awt.Font("Miriam Fixed", 1, 15)); // NOI18N
        CreditOptionButton.setForeground(new java.awt.Color(255, 255, 255));
        CreditOptionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SalesTrack/Images/credit.png"))); // NOI18N
        CreditOptionButton.setText("Credit");
        CreditOptionButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CreditOptionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreditOptionButtonMouseClicked(evt);
            }
        });
        CreditOptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditOptionButtonActionPerformed(evt);
            }
        });
        RegularOptionsPanel.add(CreditOptionButton);

        OtherOptionsPanel1.setBackground(new java.awt.Color(22, 37, 47));
        OtherOptionsPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Other options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Miriam Fixed", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        OtherOptionsPanel1.setLayout(new java.awt.GridLayout(3, 0));

        LogoutButton.setBackground(new java.awt.Color(22, 37, 47));
        LogoutButton.setFont(new java.awt.Font("Miriam Fixed", 1, 14)); // NOI18N
        LogoutButton.setForeground(new java.awt.Color(255, 255, 255));
        LogoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SalesTrack/Images/login.png"))); // NOI18N
        LogoutButton.setText("Logout");
        LogoutButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LogoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutButtonMouseClicked(evt);
            }
        });
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });
        OtherOptionsPanel1.add(LogoutButton);

        ChangePasswordButton.setBackground(new java.awt.Color(22, 37, 47));
        ChangePasswordButton.setFont(new java.awt.Font("Miriam Fixed", 1, 12)); // NOI18N
        ChangePasswordButton.setForeground(new java.awt.Color(255, 255, 255));
        ChangePasswordButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SalesTrack/Images/clear.png"))); // NOI18N
        ChangePasswordButton.setText("Change password");
        ChangePasswordButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ChangePasswordButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangePasswordButtonMouseClicked(evt);
            }
        });
        ChangePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePasswordButtonActionPerformed(evt);
            }
        });
        OtherOptionsPanel1.add(ChangePasswordButton);

        SummaryOptionButton.setBackground(new java.awt.Color(22, 37, 47));
        SummaryOptionButton.setFont(new java.awt.Font("Miriam Fixed", 1, 12)); // NOI18N
        SummaryOptionButton.setForeground(new java.awt.Color(255, 255, 255));
        SummaryOptionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SalesTrack/Images/summarry.png"))); // NOI18N
        SummaryOptionButton.setText("Pull summary");
        SummaryOptionButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SummaryOptionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SummaryOptionButtonMouseClicked(evt);
            }
        });
        SummaryOptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SummaryOptionButtonActionPerformed(evt);
            }
        });
        OtherOptionsPanel1.add(SummaryOptionButton);

        javax.swing.GroupLayout SideOptionsPanelLayout = new javax.swing.GroupLayout(SideOptionsPanel);
        SideOptionsPanel.setLayout(SideOptionsPanelLayout);
        SideOptionsPanelLayout.setHorizontalGroup(
            SideOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SideOptionsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RegularOptionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(SideOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SideOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(OtherOptionsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SideOptionsPanelLayout.setVerticalGroup(
            SideOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RegularOptionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(OtherOptionsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MiddlePanel.setBackground(new java.awt.Color(255, 255, 255));
        MiddlePanel.setLayout(new java.awt.CardLayout());

        SubHomePanel.setBackground(new java.awt.Color(255, 255, 255));

        AdminHomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdminHomeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SalesTrack/Images/homepage.png"))); // NOI18N

        javax.swing.GroupLayout SubHomePanelLayout = new javax.swing.GroupLayout(SubHomePanel);
        SubHomePanel.setLayout(SubHomePanelLayout);
        SubHomePanelLayout.setHorizontalGroup(
            SubHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 714, Short.MAX_VALUE)
            .addGroup(SubHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AdminHomeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE))
        );
        SubHomePanelLayout.setVerticalGroup(
            SubHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
            .addGroup(SubHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AdminHomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MiddlePanel.add(SubHomePanel, "card7");

        jPanel1.setBackground(new java.awt.Color(22, 37, 47));

        FooterLabel.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N
        FooterLabel.setForeground(new java.awt.Color(255, 255, 255));
        FooterLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FooterLabel.setText(" © VAG's solution  2017 ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(FooterLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FooterLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SideOptionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MiddlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SideOptionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MiddlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents
    
// <editor-fold defaultstate="collapsed" desc=" Private User-defined Methods ">

    /** 
     * Set the visibility of the panel in the card layout.
     *   Logic:
     *   First set visibility of all panel to false
     *  Then make the visibility of selected panel to true
     */
    private void SetPanelVisibility( JPanel panel ){
        
        MiddlePanel.removeAll();
        MiddlePanel.repaint();
        MiddlePanel.revalidate();
        
        MiddlePanel.add(panel);
        MiddlePanel.repaint();
        MiddlePanel.revalidate();
    }
    
    /**
     * Initializes the action panel with corresponding option
     * @param option 
     */
    private void ActionPanelInitialization(Functionality option)
    {
        // Initializes the constructor of actionPanel and passes the current object to actionPanel
        ActionPanel actionPanel = new ActionPanel(option);
        this.SetPanelVisibility(actionPanel);
    }
    
    private void SummaryActionPanelInitialization(Functionality option)
    {
        SummaryActionPanel actionPanel = new SummaryActionPanel(option);
        this.SetPanelVisibility(actionPanel);
    }

    // </editor-fold>  

    private void HomeOptionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeOptionButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeOptionButtonMouseClicked

    private void HomeOptionButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeOptionButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeOptionButtonMouseExited

    private void HomeOptionButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeOptionButtonMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeOptionButtonMouseReleased

    private void HomeOptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeOptionButtonActionPerformed
        // Setting middlepanel visibility on clicking hoem option
        this.SetPanelVisibility(SubHomePanel);
    }//GEN-LAST:event_HomeOptionButtonActionPerformed

    private void StockOptionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockOptionButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_StockOptionButtonMouseClicked

    /**
     * On clicking the course option button 
     */ 
    private void StockOptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockOptionButtonActionPerformed

        this.ActionPanelInitialization(Functionality.STOCK);
        
    }//GEN-LAST:event_StockOptionButtonActionPerformed

    private void SalesOptionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalesOptionButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SalesOptionButtonMouseClicked

    private void SalesOptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalesOptionButtonActionPerformed
        this.ActionPanelInitialization(Functionality.SALES);
    }//GEN-LAST:event_SalesOptionButtonActionPerformed

    private void IncomeOptionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IncomeOptionButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_IncomeOptionButtonMouseClicked

    private void IncomeOptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncomeOptionButtonActionPerformed
        this.ActionPanelInitialization(Functionality.INCOME);
    }//GEN-LAST:event_IncomeOptionButtonActionPerformed

    private void LogoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutButtonMouseClicked

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        try
        {
            // Logging out
            new LoginForm().setVisible(true);
            JFrame homeFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
            homeFrame.hide();
                        
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void ChangePasswordButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePasswordButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangePasswordButtonMouseClicked

    private void ChangePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePasswordButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangePasswordButtonActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        AbstractButton toggleButton = (AbstractButton)evt.getSource();
        if( toggleButton.getModel().isSelected())
        {
            SideOptionsPanel.setVisible(true);
        }
        else
        {
           SideOptionsPanel.setVisible(false);
        }        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void ExpenseOptionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExpenseOptionButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ExpenseOptionButtonMouseClicked

    private void ExpenseOptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpenseOptionButtonActionPerformed
        this.ActionPanelInitialization(Functionality.EXPENSE);
    }//GEN-LAST:event_ExpenseOptionButtonActionPerformed

    private void CreditOptionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreditOptionButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CreditOptionButtonMouseClicked

    private void CreditOptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditOptionButtonActionPerformed
        this.ActionPanelInitialization(Functionality.CREDIT);
    }//GEN-LAST:event_CreditOptionButtonActionPerformed

    private void SummaryOptionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SummaryOptionButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SummaryOptionButtonMouseClicked

    private void SummaryOptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SummaryOptionButtonActionPerformed
        this.SummaryActionPanelInitialization(Functionality.SUMMARY);
    }//GEN-LAST:event_SummaryOptionButtonActionPerformed
    
    // <editor-fold defaultstate="collapsed" desc=" Public User-defined Methods ">

    /**
     * Gets the MiddlePanel
     * Returns the middle panel of HomePanel
     */
    public JPanel GetMiddlePanel(){
        return this.MiddlePanel;
    }

    // </editor-fold>
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminHomeLabel;
    private javax.swing.JButton ChangePasswordButton;
    private javax.swing.JButton CreditOptionButton;
    private javax.swing.JButton ExpenseOptionButton;
    private javax.swing.JLabel FooterLabel;
    private javax.swing.JLabel HeaderLogoLabel;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JButton HomeOptionButton;
    private javax.swing.JButton IncomeOptionButton;
    private javax.swing.JLabel InfoLabelHeader2;
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JPanel MiddlePanel;
    private javax.swing.JPanel OtherOptionsPanel1;
    private javax.swing.JPanel RegularOptionsPanel;
    private javax.swing.JButton SalesOptionButton;
    private javax.swing.JPanel SideOptionsPanel;
    private javax.swing.JButton StockOptionButton;
    private javax.swing.JPanel SubHomePanel;
    private javax.swing.JButton SummaryOptionButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
